version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: emss-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emss_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emss-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emss-backend
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=emss_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=24h
      - BCRYPT_SALT_ROUNDS=10
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - emss-network
    command: >
      sh -c "npm run db:migrate && npm run db:seed && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emss-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - emss-network

networks:
  emss-network:
    driver: bridge

volumes:
  postgres_data:
